### PR TITLE
feat: use template as PDF footer

### PR DESCRIPTION
**Pull request by vitormattos**
Make possible use a HTML template to customize the page footer.

> **OBS 1**: For now only is possible to customize the content of footer, isn't possible to move the footer position to left, right or top of the document or put the qrcode in a custom place of document.

> **OBS 2**: The HTML generated by Twig will be used by mPDF and need to be a HTML valid to this tool.

Reference:
- https://twig.symfony.com/doc/3.x/
- https://mpdf.github.io/

I used Twig to be possible handle the vars, use conditionals, loops and other benefits of a template engine.

The follow vars is send to Twig:

|name |description|
|---|---|
|`signers`| List with display name and sign date in UNIX timestamp format of all signers. Example: `[['displayName' => 'Signer 1', 'signed' => 123456789]]` |
|`qrcodeSize`| Size in pixels of qrcode image |
|`signedBy`| Default value: Digital signed by LibreSign. |
|`linkToSite`| URL that will wrapper the `signedBy` text |
|`validateIn`| Default value: `Validate in %s.` |
|`validationSite`| The validation URL to be replaced by `%s` at `validateIn` var |
|`qrcode`| qrcode PNG image as base64 format |

Example of twig template:

```html
<table style="width:100%;border:0;font-size:8px;">
	<tr>
		{% if qrcode %}
			<td width="{{ qrcodeSize }}px">
				<img src="data:image/png;base64,{{ qrcode }}" style="width:{{ qrcodeSize }}px"/>
			</td>
		{% endif %}
		<td style="vertical-align: bottom;padding: 0px 0px 15px 0px;line-height:1.5em;">
			<a href="{{ linkToSite }}" style="text-decoration: none;color:unset;">{{ signedBy }}</a>
			{% if signers %}
				<br>
				Signers:
				{% for signer in signers %}
					{{- signer.displayName }}
					{%- if not loop.last %}, {% endif %}
				{% endfor %}
			{% endif %}
			{% if validateIn %}
				<br>
				<a href="{{ validationSite }}"
					style="text-decoration: none;color:unset;">
					{{ validateIn|replace({'%s': validationSite}) }}
				</a>
			{% endif %}
		</td>
	</tr>
</table>
```

To customize the template you will need to change the LibreSign app setting `footer_template` by twig code of your custom template.

|name|type|value|
|---|---|---|
|add_footer|boolean|Enable or not to display the footer|
|footer_signed_by|string|see up|
|footer_link_to_site|string|see up|
|validation_site|string|see up|
|footer_validate_in|string|see up|
|footer_template|string|Twig template|

## to-do

- [x] Use HTML template as PDF footer
- [x] Fix tests
- [x] Compact LibreSign package cleaning mPDF vendor folder
- [x] Add more vars to be used at footer

### CODE REVIEW

**Comment by vitormattos** [comment]
close #1305

**Comment by vitormattos** [comment]
close #808

**Comment by DazeEnd** [comment]
@vitormattos This looks like a great improvement. I’m looking forward to testing it. 👍

**Pull request merged**
