### PR TITLE
fix: style preview signatur modal like canva style

### PR DESCRIPTION
**Pull request by enieber**
close issue #1461 

replicate the style of canvas

In dark mode:

Screenshot 2023-04-12 at 02-10-23 LibreSign - Nextcloud

In Light mode:

Screenshot 2023-04-12 at 02-09-37 LibreSign - Nextcloud

### CODE REVIEW

**Review by vitormattos — COMMENTED** [review]
Nice!

I think that this solve the problem.

But have more places to apply this fix:
Scenario: Settings page
* I stay at LibreSign app
* I click on Settings
* I already created a signature
* I see:
Screenshot_20230412_070334

Scenario: Signature page
* I request to sign a document from app Files with visible signature
* I go to signature page
* I will saw this at the right tab:
Screenshot_20230412_070634


What you think about the both scenarios? Could the same fix be applied?

**Comment by enieber** [comment]
I created PreviewSignature to style one source:

Screenshot 2023-04-12 at 12-25-02 LibreSign - Nextcloud

Screenshot 2023-04-12 at 12-24-05 Nextcloud

**Pull request merged**
