### PR TITLE
l10n: Add an apostrophe

### PR DESCRIPTION
**Pull request by Valdnet**

### CODE REVIEW

**Comment by vitormattos** [comment]
@Valdnet the test failed. You need to correct the test. It is a test to verify that the failure does occur.

**Comment by Valdnet** [comment]
@vitormattos Can the apostrophe `\'` be used in this form? If not then please give me a suggestion for improvement.

**Comment by vitormattos** [comment]
Yes, is possible. You also need to change it in the test.

**Comment by Valdnet** [comment]
> You also need to change it in the test.

Hmm. How to do it?

**Comment by vitormattos** [comment]
In the broken test it says where you should correct it.

Click on details

image

You will see the file and the failed test method

image

It is this line that needs to be changed

https://github.com/LibreSign/libresign/blob/main/tests/Unit/Service/AccountServiceTest.php#L94

Another possibility is to search for a part of the text to find all occurrences

**Comment by Valdnet** [comment]
@vitormattos Thanks for the clarification 😉.
PR: #137

**Comment by rakekniven** [comment]
"Don't is your file" sounds a bit strange for me.
Idea: Is not your file

What do you think.

**Comment by Valdnet** [comment]
@rakekniven I was wondering about that too :wink:. I think it should be consistent with this: https://github.com/LibreSign/libresign/blob/99d9ca0c534dec514bad57bf40f35cae8172757a/lib/Helper/JSConfigHelper.php#L83

**Comment by Valdnet** [comment]
ping @vitormattos
Can the two messages be the same?

**Comment by vitormattos** [comment]
`This is not your file` is the same as `Is not your file`. 
Very similar. Long form is better?

**Comment by rakekniven** [comment]
Please align it to your other messages. You mostley write in short form like `Empty file` and not `This is an empty file`.

**Comment by Valdnet** [comment]
@vitormattos But can the text string `Don't is your file` be changed to `This is not your file`.
Will it be as expected?

**Comment by Valdnet** [comment]
@rakekniven But it's not about an empty file 😉.

**Comment by vitormattos** [comment]
Correct, it is about a file that was not designed to be signed by the authenticated person.

**Comment by rakekniven** [comment]
> But it's not about an empty file

This was just an example about long and short forms.

This has been merged in the meantime. I am fine with your changes.

**Comment by Valdnet** [comment]
> This was just an example about long and short forms.

I understood now 😉.
Cheers!

**Pull request merged**
