### PR TITLE
Remove unused method

### PR DESCRIPTION
**Pull request by vitormattos**
I made a grep to find by this method. Is an unused method

### CODE REVIEW

**Comment by giovannism20** [comment]
Can u explain more about this grep ?

**Comment by vitormattos** [comment]
Not exactly a grep but I made a search at my IDE and didn't found any reference to these methods.

```
getInfoOfFileToSignUsingSignRequestUuid
getInfoOfFileToSignUsingFileUuid
```

**Comment by giovannism20** [comment]
So maybe would be more interesting if we make some manual tests just to guarantee it

**Comment by vitormattos** [comment]
The previous context:
Before to implement the identify methods logic, all the logic to validate the signer was made by these methods.
Part of logic was moved to identify methods classes, in particular the logic that throw exceptions and validate if the file was signed.
The other part, that return data, was moved to other points of code because, as is possible to see at removed unit test, was very hard to maintain the methods. Was methods with a lot of responsibility and I followed removing the dependency of them. Now, when I started to look the code to make a task, I identified that haven't any place using them.

**Review by giovannism20 — APPROVED** [review]

**Pull request merged**
